name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create .env file from secrets
      run: |
        echo "PORT=${{ secrets.PORT }}" >> backend/.env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend/.env

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: "ton-app-service"
        slot-name: "production"
        package: ./backend
